server:
  port: 9999
spring:
  application:
    name: springJpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update  # if table is not sure, switch to create-drop
  profiles:
    include:
      - dev